# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: "http://zephyrtransport.org"
url_secure: "https://zephyr-membership.surge.sh"

title: Zephyr Foundation for Advancing Travel Analysis Methods

email: info@zephyrtransport.org
author: Elizabeth Sall
description: The Zephyr Foundation’s mission is to advance rigorous transportation and land use decision-making for the public good by advocating for and supporting improved travel analysis and facilitating its implementation.
copyright: 'Copyright &copy; 2018 Zephyr Foundation. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

collections:
    events:
        output: true
    memberships:
        output: false
    projects:
        output: false
    trb17projects:
        output: true


# ----------------------- #
#   Stripe Settings       #
# ----------------------- #
post_url: https://zephyr-membership.herokuapp.com/
stripe_key: pk_test_3H900QQseJBoByGKOakot25V

products:
  - name: Standard Annual Subscription
    price: 20000
    price_pretty: $200.00
    description: Annual recurring membership for regular members

  - name: Standard 1-Year Membership
    price: 20000
    price_pretty: $200.00
    description: One-time 1-year membership for regular members

  - name: Student Annual Subscription
    price: 2000
    price_pretty: $20.00
    description: Annual recurring membership for student/youth members

  - name: Student 1-Year Membership
    price: 2000
    price_pretty: $20.00
    description: One-time 1-year membership for student/youth members




# ----------------------- #
#   Look Settings         #
# ----------------------- #

top-bg-img: tunnel-swoosh-bg.jpg
bottom-bh-img: nyc-bg.jpg
highlight-color: 00aced         #turquoise blue
dark-gray-color: 2F4F4F         #dark gray
background-highlight: fafafa    #light gray - blueish
highlight-text: f8f8f8          #light gray


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/zephyrtransport
  - title: github
    url: https://github.com/zephyrtransport
  - title: email list
    url: http://eepurl.com/ccQL7z

